"""Enforce the source-only record policy in label_rules.yaml."""

from pathlib import Path

import yaml

from .core import digest

FIELDS = {"_id", "chunk_text", "content_type", "filename", "drive_path", "source_url", "pages", "topics"}
CONTENT_TYPES = ["table", "figure", "text"]


def load_rules():
    raw = (Path.cwd() / "label_rules.yaml").read_text(encoding="utf-8")
    rules = yaml.safe_load(raw)
    if not isinstance(rules, dict) or set(rules) != FIELDS:
        raise ValueError("label_rules.yaml must specify exactly the eight allowed record fields")
    if rules["content_type"] != CONTENT_TYPES:
        raise ValueError("content_type must be [table, figure, text]")
    return digest(raw)


def apply_source_labels(blocks):
    # Headings are extracted from the source by Docling, never generated by a model.
    for block in blocks:
        if block.kind not in CONTENT_TYPES:
            raise ValueError(f"Unsupported content_type: {block.kind}")
        block.details["topics"] = list(dict.fromkeys(h for h in block.headings if h.strip()))
    for position, block in enumerate(blocks):
        if block.kind != "figure":
            continue
        neighbor = next(
            (b for b in reversed(blocks[:position]) if b.kind == "text" and b.headings == block.headings),
            None,
        )
        if neighbor is None:
            neighbor = next(
                (b for b in blocks[position + 1 :] if b.kind == "text" and b.headings == block.headings),
                None,
            )
        block.text = neighbor.text if neighbor else ""
        block.details.pop("annotation", None)
        block.details.pop("annotation_method", None)
        block.details["topics"] = neighbor.details["topics"].copy() if neighbor else []


def validate_record(record):
    if set(record) != FIELDS:
        raise ValueError("Record must contain exactly the eight fields allowed by label_rules.yaml")
    if record["content_type"] not in CONTENT_TYPES:
        raise ValueError("Invalid content_type")
    for field in ("_id", "chunk_text", "filename", "drive_path", "source_url"):
        if not isinstance(record[field], str):
            raise ValueError(f"{field} must be a string")
    for field in ("pages", "topics"):
        if not isinstance(record[field], list) or not all(isinstance(v, str) for v in record[field]):
            raise ValueError(f"{field} must be a list of strings")
